var be=CardOpenCC({from:"cn",to:"tw"}),Ce=["\u91CD\u65B0\u5904\u7406\u53D8\u91CF","\u91CD\u65B0\u8BFB\u53D6\u521D\u59CB\u53D8\u91CF","\u6E05\u9664\u65E7\u697C\u5C42\u53D8\u91CF","\u5FEB\u7167\u697C\u5C42","\u91CD\u6F14\u697C\u5C42","\u91CD\u8BD5\u989D\u5916\u6A21\u578B\u89E3\u6790"],ee=[...Ce,"UpdateVariable","Analysis","JSONPatch","StatusPlaceHolderImpl","initvar","mvu_update","stat_data","tavern_helper","TavernHelper_scripts","export_with","getButtonEvent","registerMvuSchema"],U=e=>JSON.parse(JSON.stringify(e)),te=e=>/[\u3400-\u9fff]/u.test(e);
function V(e,t="$",o=[]){return typeof e=="string"?o.push({path:t,value:e}):Array.isArray(e)?e.forEach((r,n)=>V(r,`${t}/${n}`,o)):e&&typeof e=="object"&&Object.entries(e).forEach(([r,n])=>V(n,`${t}/${r}`,o)),o}
function E(e){return e?.data&&typeof e.data=="object"?e.data:e}
function R(e){return E(e)?.character_book?.entries||[]}
function M(e){let t=E(e)?.extensions||{};return Array.isArray(t.tavern_helper?.scripts)?t.tavern_helper.scripts:Array.isArray(t.TavernHelper_scripts)?t.TavernHelper_scripts:[]}
function Ae(e){return E(e)?.extensions?.regex_scripts||[]}
function Ue(e){let t=new Set(ee);for(let o of M(e)){let r=String(o.content||"");for(let n of r.matchAll(/(?:const|let|var|class|function)\s+([\p{L}_$][\p{L}\p{N}_$]*)/gu))t.add(n[1]);for(let n of r.matchAll(/^\s*([\p{Script=Han}\w_$]+)\s*:\s*z\./gmu))t.add(n[1]);for(let n of r.matchAll(/stat_data(?:\??\.([\p{Script=Han}\w_$]+))+/gu))for(let i of n[0].matchAll(/\.([\p{Script=Han}\w_$]+)/gu))t.add(i[1]);for(let n of r.matchAll(/z\.enum\(\[([^\]]+)\]\)/gu))for(let i of n[1].matchAll(/["']([^"']+)["']/gu))t.add(i[1])}for(let{value:o}of V(e))for(let r of o.matchAll(/["']path["']\s*:\s*["']([^"']+)["']/gu))r[1].split("/").filter(Boolean).forEach(n=>t.add(n.replace(/~1/g,"/").replace(/~0/g,"~")));for(let o of R(e)){let r=`${o.comment||o.name||""}
${o.content||""}`;if(/(?:\[initvar\]|\[mvu_update\]|变量初始化|變量初始化|变量更新规则|變量更新規則)/iu.test(r))for(let n of String(o.content||"").split(/\r?\n/u)){let i=n.match(/^\s*(?:[-]\s*)?([^:#{}\[\],]+?)\s*:\s*(?:$|[^/])/u);if(i){let s=i[1].trim();te(s)&&!/^(?:type|range|format|check)$/u.test(s)&&t.add(s)}}}return[...t].filter(Boolean).sort((o,r)=>r.length-o.length)}
function Ve(e,t){let o=[],r=s=>{let a=`\uE000${o.length}\uE001`;return o.push(s),a},n=e,i=[/https?:\/\/[^\s"'<>]+/gu,/\{\{[\s\S]*?\}\}/gu,/\[[A-Za-z_][^\]]*\]/gu,/\b[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\b/giu];for(let s of i)n=n.replace(s,r);for(let s of t)!s||!n.includes(s)||(n=n.split(s).join(r(s)));return{masked:n,restore:s=>{let a=s;for(let c=0;c<=o.length;c+=1){let l=a.replace(/\uE000(\d+)\uE001/gu,(f,g)=>o[Number(g)]);if(l===a)break;a=l}return a}}}
function q(e,t){if(!te(e))return{value:e,kept:[]};let{masked:o,restore:r}=Ve(e,t);return{value:r(be(o)).replace(/(?:简体|簡體)中文/gu,"\u7E41\u9AD4\u4E2D\u6587").replace(/zh-cn/giu,"zh-tw"),kept:t.filter(n=>n&&e.includes(n))}}
function $e(e,t){return/\/(?:id|spec|spec_version|type|role|position|source|destination|placement)$/u.test(e)?"\u683C\u5F0F\u3001ID \u6216\u5217\u8209\u503C":/\/button\/buttons\/\d+\/name$/u.test(e)?"Mini MVU \u56FA\u5B9A\u6309\u9215\u6697\u865F":/\/export_with(?:\/|$)/u.test(e)?"\u9152\u9928\u52A9\u624B\u532F\u51FA\u8A2D\u5B9A":!t&&/\/findRegex$/u.test(e)?"\u6B63\u5247\u641C\u5C0B\u5F0F":""}
function K(e,t,o,r="$",n=[],i=[]){if(Array.isArray(e))return e.forEach((s,a)=>{let c=`${r}/${a}`;if(typeof s=="string"){let l=$e(c,o);if(l)i.push({path:c,value:s,reason:l});else{let f=q(s,t);f.value!==s&&(e[a]=f.value,n.push({path:c,before:s,after:f.value})),f.kept.length&&i.push({path:c,value:f.kept.join("\u3001"),reason:"\u53D7\u4FDD\u8B77\u6280\u8853\u8B58\u5225\u5B57"})}}else s&&typeof s=="object"&&K(s,t,o,c,n,i)}),{changes:n,preserved:i};if(!e||typeof e!="object")return{changes:n,preserved:i};for(let[s,a]of Object.entries(e)){let c=`${r}/${s}`;if(typeof a=="string"){let l=$e(c,o);if(l)i.push({path:c,value:a,reason:l});else{let f=q(a,t);f.value!==a&&(e[s]=f.value,n.push({path:c,before:a,after:f.value})),f.kept.length&&i.push({path:c,value:f.kept.join("\u3001"),reason:"\u53D7\u4FDD\u8B77\u6280\u8853\u8B58\u5225\u5B57"})}}else a&&typeof a=="object"&&K(a,t,o,c,n,i)}return{changes:n,preserved:i}}
function Be(e,t){return t.split("/").slice(1).reduce((o,r)=>o?.[r],e)}
function Je(e,t,o){let r=V(e);return o.map(({before:n,after:i})=>{let s=r.filter(c=>c.value.includes(n)).map(c=>c.path),a=s.filter(c=>{let l=Be(t,c);return typeof l!="string"||!l.includes(i)||n!==i&&l.includes(n)});return{before:n,after:i,paths:s,failures:a,ok:a.length===0}}).filter(n=>n.paths.length)}
function B(e,t,o="$",r=[]){if(typeof e!=typeof t||Array.isArray(e)!==Array.isArray(t))return r.push(`${o} \u7684\u8CC7\u6599\u578B\u5225\u6539\u8B8A`),r;if(Array.isArray(e))e.length!==t.length&&r.push(`${o} \u7684\u9663\u5217\u9577\u5EA6\u6539\u8B8A`),e.slice(0,t.length).forEach((n,i)=>B(n,t[i],`${o}/${i}`,r));else if(e&&typeof e=="object"){let n=Object.keys(e).sort(),i=Object.keys(t).sort();JSON.stringify(n)!==JSON.stringify(i)&&r.push(`${o} \u7684 JSON \u6B04\u4F4D\u88AB\u65B0\u589E\u6216\u522A\u9664`);for(let s of n.filter(a=>a in t))B(e[s],t[s],`${o}/${s}`,r)}else typeof e!="string"&&e!==t&&r.push(`${o} \u7684\u975E\u6587\u5B57\u503C\u88AB\u6539\u52D5`);return r}
function we(e){let t=[],o=E(e),r=(n,i="$")=>{if(!(!n||typeof n!="object")){if(Array.isArray(n))return n.forEach((s,a)=>r(s,`${i}/${a}`));for(let[s,a]of Object.entries(n)){let c=`${i}/${s}`;(/\/(?:id|spec|spec_version)$/u.test(c)||/\/button\/buttons\/\d+\/name$/u.test(c))&&typeof a=="string"&&t.push([c,a]),r(a,c)}}};r(e);for(let n of M(e))n.export_with&&t.push([`script:${n.id}:export_with`,JSON.stringify(n.export_with)]);return t}
function Re(e,t){let o=new Map(we(e)),r=new Map(we(t)),n=[];for(let[i,s]of o)r.get(i)!==s&&n.push(`${i} \u4E0D\u53EF\u7FFB\u8B6F\u6216\u907A\u5931`);return n}
function We(e){let t=new Set;for(let o of M(e)){let r=String(o.content||"");if(/registerMvuSchema|const\s+Schema\s*=\s*z\.object/u.test(r))for(let n of r.matchAll(/^\s*([\p{Script=Han}\w_$]+)\s*:\s*z\./gmu))t.add(n[1])}return t}
function Y(e){let t=We(e);if(!t.size)return[];let o=[],r=[["\u76EE\u524D\u65E5\u671F","\u7576\u524D\u65E5\u671F"],["\u76EE\u524D\u65F6\u95F4","\u5F53\u524D\u65F6\u95F4"],["\u76EE\u524D\u6642\u9593","\u7576\u524D\u6642\u9593"],["\u653B\u7565\u70B9\u6570","\u653B\u7565\u79EF\u5206"],["\u653B\u7565\u9EDE\u6578","\u653B\u7565\u7A4D\u5206"],["\u82B1\u8D39\u70B9\u6570","\u82B1\u8D39\u79EF\u5206"],["\u82B1\u8CBB\u9EDE\u6578","\u82B1\u8CBB\u7A4D\u5206"]];for(let n of R(e)){let i=n.comment||n.name||`UID ${n.id}`,s=String(n.content||"");if(/(?:\[initvar\]|\[mvu_update\]|变量初始化|變量初始化|变量更新规则|變量更新規則)/iu.test(`${i}
${s}`))for(let[a,c]of r)s.includes(a)&&t.has(c)&&o.push(`${i} \u4F7F\u7528\u300C${a}\u300D\uFF0CSchema \u4F7F\u7528\u300C${c}\u300D`)}return o}
function He(e,t={}){let o=t.linked!==!1,r=U(e),n=U(e),i=Y(r),s=Ue(r),a=o?ee:s,c=o?s.filter(d=>te(d)&&!Ce.includes(d)).map(d=>({before:d,after:be(d)})).filter(d=>d.before!==d.after):[],l=new Map;for(let d of c){let I=l.get(d.after)||[];I.push(d.before),l.set(d.after,I)}let f=[...l].filter(([,d])=>new Set(d).size>1).map(([d,I])=>`\u591A\u500B\u8B58\u5225\u5B57\u6703\u5408\u4F75\u6210\u300C${d}\u300D\uFF1A${[...new Set(I)].join("\u3001")}`),{changes:g,preserved:C}=K(n,a,o),z=o?Je(r,n,c):[],Q=[...B(r,n),...Re(r,n),...f,...z.filter(d=>!d.ok).map(d=>`\u8B58\u5225\u5B57\u300C${d.before}\u300D\u672A\u5728\u6240\u6709\u5F15\u7528\u8655\u540C\u6B65\u8F49\u6210\u300C${d.after}\u300D`)],G=Y(n);return{output:n,changes:g,preserved:C,mapping:c,linkChecks:z,tokens:s,errors:Q,sourceWarnings:i,outputWarnings:G}}
function Qe(e){let t=[],o=E(e);return(!e||typeof e!="object")&&t.push("\u6A94\u6848\u4E0D\u662F JSON \u7269\u4EF6"),e.spec&&e.spec!=="chara_card_v3"&&t.push(`\u76EE\u524D\u50C5\u5B8C\u6574\u652F\u63F4 chara_card_v3\uFF0C\u5075\u6E2C\u5230 ${e.spec}`),o?.character_book?.entries||t.push("\u627E\u4E0D\u5230\u89D2\u8272\u5361\u5167\u5D4C\u4E16\u754C\u66F8"),{errors:t,warnings:Y(e)}}
function Ge(e){return{name:E(e)?.name||e?.name||"\u672A\u547D\u540D\u89D2\u8272",spec:e?.spec||"\u672A\u77E5",entries:R(e).length,regexes:Ae(e).length,scripts:M(e).length}}
function ne(e){return e?.spec==="chara_card_v3"||e?.data?.character_book||e?.character_book?"card":Array.isArray(e?.prompts)||Array.isArray(e?.prompt_order)?"preset":"unknown"}
function Fe(e){return/^\$\/name$/u.test(e)?"Preset \u540D\u7A31":/^\$\/prompts\/\d+\/(?:name|content)$/u.test(e)?"Prompt \u53EF\u8B80\u6587\u5B57":/^\$\/extensions\/regex_scripts\/\d+\/(?:scriptName|findRegex|replaceString)$/u.test(e)?"Regex \u986F\u793A\u6216\u5339\u914D\u6587\u5B57":/\/(?:story_string|chat_start|example_separator|assistant_prefill)$/u.test(e)?"Preset \u6A21\u677F\u6587\u5B57":/\/(?:prompt|format)$/u.test(e)||/\/(?:[^/]+_prompt|[^/]+_format)$/u.test(e)?"Preset \u63D0\u793A\u6216\u683C\u5F0F\u6587\u5B57":""}
function Z(e,t="$",o=[],r=[]){if(Array.isArray(e))return e.forEach((n,i)=>{let s=`${t}/${i}`;n&&typeof n=="object"&&Z(n,s,o,r)}),{changes:o,preserved:r};if(!e||typeof e!="object")return{changes:o,preserved:r};for(let[n,i]of Object.entries(e)){let s=`${t}/${n}`;if(typeof i=="string")if(Fe(s)){let c=q(i,ee);c.value!==i&&(e[n]=c.value,o.push({path:s,before:i,after:c.value})),c.kept.length&&r.push({path:s,value:c.kept.join("\u3001"),reason:"\u53D7\u4FDD\u8B77\u6280\u8853\u6A19\u8A18"})}else/\/(?:identifier|id|role|model|chat_completion_source|source|type)$/u.test(s)&&r.push({path:s,value:i,reason:"Preset \u8B58\u5225\u5B57\u6216\u7CFB\u7D71\u8A2D\u5B9A"});else i&&typeof i=="object"&&Z(i,s,o,r)}return{changes:o,preserved:r}}
function J(e){let t=(e?.prompts||[]).map((r,n)=>({path:`$/prompts/${n}/identifier`,value:r?.identifier})),o=[];return(e?.prompt_order||[]).forEach((r,n)=>{(r?.order||[]).forEach((i,s)=>o.push({path:`$/prompt_order/${n}/order/${s}/identifier`,value:i?.identifier}))}),{promptIds:t,orderIds:o}}
function ke(e){let{promptIds:t,orderIds:o}=J(e),r=[],n=t.map(c=>c.value).filter(c=>typeof c=="string"),i=[...new Set(n.filter((c,l)=>n.indexOf(c)!==l))];i.length&&r.push(`Prompt identifier \u91CD\u8907\uFF1A${i.join("\u3001")}`);let s=new Set(n),a=[...new Set(o.map(c=>c.value).filter(c=>typeof c=="string"&&!s.has(c)))];return a.length&&r.push(`prompt_order \u5F15\u7528\u4E86\u4E0D\u5B58\u5728\u7684 identifier\uFF1A${a.join("\u3001")}`),r}
function Xe(e,t){let o=J(e),r=J(t),n=[];return JSON.stringify(o)!==JSON.stringify(r)&&n.push("Prompt identifier \u6216 prompt_order \u5F15\u7528\u5728\u7FFB\u8B6F\u671F\u9593\u88AB\u6539\u52D5"),n}
function qe(e){let t=U(e),o=U(e),{changes:r,preserved:n}=Z(o),i=J(o),s=i.orderIds.map(c=>({before:c.value,after:c.value,paths:[c.path],failures:i.promptIds.some(l=>l.value===c.value)?[]:[c.path],ok:i.promptIds.some(l=>l.value===c.value)})),a=[...B(t,o),...Xe(t,o),...ke(o)];return{output:o,changes:r,preserved:n,mapping:[],linkChecks:s,tokens:[],errors:a,sourceWarnings:[],outputWarnings:[]}}
function Ke(e){let t=[];return(!e||typeof e!="object"||Array.isArray(e))&&t.push("\u6A94\u6848\u4E0D\u662F Preset JSON \u7269\u4EF6"),Array.isArray(e?.prompts)||t.push("\u627E\u4E0D\u5230 prompts \u9663\u5217"),e?.prompt_order!=null&&!Array.isArray(e.prompt_order)&&t.push("prompt_order \u4E0D\u662F\u9663\u5217"),t.push(...ke(e)),{errors:t,warnings:[]}}
function Ee(e){let t=ne(e);return t==="card"?{...He(e),type:t}:t==="preset"?{...qe(e),type:t}:{output:e,changes:[],preserved:[],mapping:[],linkChecks:[],tokens:[],errors:["\u7121\u6CD5\u8FA8\u8B58\u6A94\u6848\u662F V3 \u89D2\u8272\u5361\u6216 Preset"],sourceWarnings:[],outputWarnings:[],type:t}}
function Se(e){let t=ne(e);return t==="card"?{...Qe(e),type:t}:t==="preset"?{...Ke(e),type:t}:{errors:["\u7121\u6CD5\u8FA8\u8B58\u6A94\u6848\u662F V3 \u89D2\u8272\u5361\u6216 Preset"],warnings:[],type:t}}
function _e(e){let t=ne(e);if(t==="card")return{...Ge(e),type:t,detail:`\u4E16\u754C\u66F8 ${R(e).length}\uFF5C\u6B63\u5247 ${Ae(e).length}\uFF5C\u8173\u672C ${M(e).length}`};if(t==="preset"){let o=e?.extensions?.regex_scripts?.length||0,r=(e?.prompts||[]).filter(n=>n?.enabled!==!1).length;return{name:e?.name||"\u672A\u547D\u540D Preset",spec:"SillyTavern Preset",type:t,detail:`Prompts ${r}/${e?.prompts?.length||0}\uFF5C\u6B63\u5247 ${o}`}}return{name:"\u7121\u6CD5\u8FA8\u8B58",spec:"\u672A\u77E5",type:t,detail:"\u2014"}}var oe=new TextEncoder;
function Ye(e){let t=4294967295;for(let o of e){t^=o;for(let r=0;r<8;r+=1)t=t>>>1^3988292384&-(t&1)}return(t^4294967295)>>>0}
function re(...e){let t=e.reduce((n,i)=>n+i.length,0),o=new Uint8Array(t),r=0;for(let n of e)o.set(n,r),r+=n.length;return o}
function xe(e){let t=new Uint8Array(4);return new DataView(t.buffer).setUint32(0,e),t}
function Ze(e,t){let o=oe.encode(e);return re(xe(t.length),o,t,xe(Ye(re(o,t))))}
function et(e){let t=atob(e),o=Uint8Array.from(t,r=>r.charCodeAt(0));return new TextDecoder().decode(o)}
function tt(e){let t=oe.encode(e),o="";for(let r=0;r<t.length;r+=8192)o+=String.fromCharCode(...t.subarray(r,r+8192));return btoa(o)}
function Ne(e){let t=new Uint8Array(e);if(![137,80,78,71,13,10,26,10].every((a,c)=>t[c]===a))throw new Error("\u4E0D\u662F\u6709\u6548\u7684 PNG \u6A94\u6848");let r=[],n=8,i=null,s=null;for(;n+12<=t.length;){let a=new DataView(e,n,4).getUint32(0),c=new TextDecoder().decode(t.subarray(n+4,n+8)),l=t.subarray(n+8,n+8+a);if(r.push({type:c,data:new Uint8Array(l),raw:t.slice(n,n+12+a)}),c==="tEXt"){let f=l.indexOf(0);if(f>0){let g=new TextDecoder().decode(l.subarray(0,f));if(g==="ccv3"||g==="chara"&&!i)try{i=JSON.parse(et(new TextDecoder("latin1").decode(l.subarray(f+1)))),s=g}catch{}}}if(n+=12+a,c==="IEND")break}if(!i)throw new Error("PNG \u88E1\u627E\u4E0D\u5230 SillyTavern chara\uFF0Fccv3 metadata");return{card:i,chunks:r,keyword:s,original:t}}
function Pe(e,t){let o=oe.encode(`${e.keyword}\0${tt(JSON.stringify(t))}`),r=[e.original.slice(0,8)],n=!1;for(let i of e.chunks){if(i.type==="tEXt"){let s=i.data.indexOf(0);if((s>0?new TextDecoder().decode(i.data.subarray(0,s)):"")===e.keyword){n||r.push(Ze("tEXt",o)),n=!0;continue}}r.push(i.raw)}if(!n)throw new Error("\u7121\u6CD5\u5B9A\u4F4D\u539F\u59CB\u89D2\u8272\u5361 metadata");return re(...r)}